# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SpsToolbox
                                 A QGIS plugin
 Laver xml snippets til Spatial Suite konfiguration
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-10-19
        copyright            : (C) 2021 by Daníel Örn Árnason
        email                : daarn@slagelse.dk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SpsToolbox class from file SpsToolbox.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sps_toolbox import SpsToolbox
    return SpsToolbox(iface)
